x-deploy: &deploy
  deploy:
    restart_policy:
      condition: on-failure
      delay: 5s
      max_attempts: 3
      window: 120s

services:
  server:
    depends_on:
      - db
    build: .
    image: ammarshah/todoer-server:latest
    env_file: .env
    ports:
      - 80:3000
    <<: *deploy

  db:
    image: postgres:16.1
    env_file: .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    <<: *deploy

volumes:
  postgres:
