databases:
  - name: todoer_db
    databaseName: todoer_production
    user: todoer
    plan: free
    region: oregon
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    postgresMajorVersion: "17"

services:
  - type: web
    name: todoer
    runtime: ruby
    plan: free
    region: oregon
    repo: https://gitlab.com/ammarvellous/todoer
    branch: master
    autoDeploy: true
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec rails server
    healthCheckPath: /up
    envVars:
      - key: SECRET_KEY_BASE
        sync: false
      - key: APP_DOMAIN
        value: todoer-9s1j.onrender.com
      - key: APP_PORT
        value: DUMMY
      - key: SMTP_ADDRESS
        value: smtp-relay.brevo.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: DEFAULT_REPLY_TO_EMAIL
        sync: false
      - key: TODOER_SUPPORT_EMAIL
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: todoer_db
          property: connectionString
      - key: POSTGRES_HOST
        value: DUMMY
      - key: POSTGRES_USERNAME
        value: DUMMY
      - key: POSTGRES_PASSWORD
        value: DUMMY
      - key: WEB_CONCURRENCY
        value: 2
