services:
  - type: web
    name: todoer
    runtime: ruby
    plan: free
    region: oregon
    repo: https://gitlab.com/ammarvellous/todoer
    branch: master
    autoDeploy: true
    buildCommand: ./bin/render-build.sh
    startCommand: ./bin/thrust ./bin/rails server
    healthCheckPath: /up
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: APP_DOMAIN
        value: todoer-9s1j.onrender.com
      - key: SOLID_QUEUE_IN_PUMA
        value: true
      - key: WEB_CONCURRENCY
        value: 2
