# This file is a template for all the credentials added in credentials.yml.enc.
#
# You may only use this file if you lose the master.key file to decrypt the existing
# credentials.yml.enc file.
#
# In that case, you can run `bin/rails credentials:edit` to create a new credentials.yml.enc and a master.key file,
# and then copy the content of this file into the new one.

# Generate using `rails secret` command
secret_key_base: secret_key_base

# Generate a new SMTP key here: https://app.brevo.com/settings/keys/smtp
# and then set "Login" and "SMTP key value" as user_name and password, respectively.
smtp:
  user_name: user_name
  password: password
