<%
  default_opts = "--publish-quiet --format #{ENV['CUCUMBER_FORMAT'] || 'progress'}"

  std_opts = "--strict --tags 'not @wip'"

  rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
  rerun = rerun.strip.gsub /\s/, ' '
  rerun_opts = rerun.empty? ? "features" : "#{rerun}"
%>

default: <%= default_opts %> <%= std_opts %> features
wip:     <%= default_opts %> --tags @wip:3 --wip features
rerun:   <%= default_opts %> <%= std_opts %> <%= rerun_opts %> --format rerun --out rerun.txt
